{{- if .Values.remoteCluster -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relaychain-alice
  labels: {{- include "relaychain-testnet.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "relaychain-alice-ws-{{ .Values.env }}.{{ .Values.domainZone }}"
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: "relaychain-alice-ws-{{ .Values.env }}.{{ .Values.domainZone }}"
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: relaychain-alice
              port:
                number: 9944
  tls:
    - hosts:
        - "relaychain-alice-ws-{{ .Values.env }}.{{ .Values.domainZone }}"
      secretName: relaychain-alice-tls
{{- end }}
