{{ $name :=  "relaychain-bob" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels: {{- include "relaychain-testnet.labels" . | nindent 4 }}
    service: {{ $name }}
spec:
  ports:
    - port: 30333
      name: p2p-port
    - port: 9944
      name: rpc
  selector:
    {{- include "relaychain-testnet.selectorLabels" . | nindent 4 }}
    service: {{ $name }}
