{{ $name :=  "relaychain-bob" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels: {{- include "relaychain-testnet.labels" . | nindent 4 }}
    service: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "relaychain-testnet.selectorLabels" . | nindent 6 }}
      service: {{ $name }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "relaychain-testnet.labels" . | nindent 8 }}
        service: {{ $name }}
    spec:
      initContainers:
        - name: chainspec-generator
          image: {{ .Values.image | quote }}
          command: ["/bin/bash"]
          args: 
            - -c
            - |
              set -eux -o pipefail
              {{- if not .Values.forceGenerateChainspec }}
              if [ ! -f {{ .Values.chainspecPath }} ]; then
              {{- end }}
                /usr/bin/polkadot build-spec --chain={{ .Values.chain }} --disable-default-bootnode --raw > {{ .Values.chainspecPath }}
              {{- if not .Values.forceGenerateChainspec }}
              fi
              {{- end }}
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
      containers:
        - name: {{ $name }}
          image: {{ .Values.image | quote }}
          command:
            - /usr/bin/polkadot
            - --chain={{ .Values.chainspecPath }}
            - --validator
            - --unsafe-ws-external
            - --rpc-port=9944
            - --port=30333
            - --unsafe-rpc-external
            - --rpc-cors=all
            - --prometheus-external
            - --prometheus-port=9616
            - --bootnodes=/dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
            - --bob
             {{- if .Values.basePath }}
            - --base-path={{ .Values.basePath }}
            {{- end }}
            {{- range .Values.bobExtraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - containerPort: 9616
            - containerPort: 9944
            - containerPort: 30333
          env:
            {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
            - mountPath: /polkadot/.local/share/polkadot
              name: chaindata
      volumes:
        - name: node-chainspec-volume
          emptyDir: {}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: chaindata
      spec:
        storageClassName: {{ .Values.storageClass }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storageSize }}
