{{- if .Values.podDisruptionBudget.enabled -}}
{{- if or (gt .Values.replicaCount 1.0) ( and (.Values.autoscaling.enabled) (gt .Values.autoscaling.minReplicas 1.0) )  }}
################################################
# Standardized Templates - Pod Disruption Budget (pdb)
################################################
apiVersion: {{ template "pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "name" . }}
spec:
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
  selector:
    matchLabels:
{{- if .Values.labelsEnableDefault }}
      app.kubernetes.io/name: {{ template "name" . }}
{{- end }}

{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 6 }}
{{- end }}
{{- end }}
{{- end }}