{{- if and .Values.remoteCluster .Values.enableWsIngress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "node.name" . }}
  labels: {{- include "node.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "node.name" . }}-ws-{{ .Values.environment }}.{{ .Values.domainZone }}
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ include "node.name" . }}-ws-{{ .Values.environment }}.{{ .Values.domainZone }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ include "node.name" . }}
              port:
                number: 9944
    {{- if .Values.substrateApiSidecar.enabled }}
    - host: {{ include "node.name" . }}-api-{{ .Values.environment }}.{{ .Values.domainZone }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ include "node.name" . }}
              port:
                number: 8080
    {{- end }}
  tls:
    - hosts:
        - {{ include "node.name" . }}-ws-{{ .Values.environment }}.{{ .Values.domainZone }}
        {{- if .Values.substrateApiSidecar.enabled }}
        - {{ include "node.name" . }}-api-{{ .Values.environment }}.{{ .Values.domainZone }}
        {{- end }}
      secretName: {{ include "node.name" . }}-tls
{{- end }}