{{- if .Values.enablePodMonitoringCollectors }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "node.name" . }}
  labels: {{- include "node.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
    service: {{ include "node.name" . }}
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 30s  
  - port: prom-relaychain
    path: /metrics
    interval: 30s
{{- end }}