{{- range $keys := .Values.node.accountKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "node.name" $ }}-{{ .type }}"
data:
  type: {{ .type | b64enc }}
  scheme: {{ .scheme | b64enc }}
  seed: {{ .seed | b64enc }}
{{- end }}