apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.name" . }}
  labels: {{- include "node.labels" . | nindent 4 }}
    service: {{ include "node.name" . }}
    isP2P: 'false'
spec:
  type: ClusterIP
  ports:
    - port: 9944
      name: rpc
    - port: 9615
      name: prometheus
    {{- if .Values.isParachain }}
    - port: 9625
      name: prom-relaychain
    {{- end }}
    {{- if .Values.wsHealthExporter.enabled }}
    - port: 8001
      name: http-ws-health
      targetPort: http-ws-health
    {{- end }}
    {{- if .Values.substrateApiSidecar.enabled }}
    - port: 8080
      name: api-sidecar
      targetPort: api-sidecar
    {{- if .Values.substrateApiSidecar.metrics.enabled }}
    - port: {{ .Values.substrateApiSidecar.metrics.port | int }}
      name: prom-sidecar
      targetPort: prom-sidecar
    {{- end }}
    {{- end }}
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
    service: {{ include "node.name" . }}