apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.name" . }}-p2p
  {{- if .Values.remoteCluster }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "node.name" . }}-p2p-{{ .Values.environment }}.{{ .Values.domainZone }}
  {{- end }}
  labels: {{- include "node.labels" . | nindent 4 }}
    service: {{ include "node.name" . }}
    isP2P: 'true'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 30333
      name: p2p-port
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
    service: {{ include "node.name" . }}