# Default values for mangata-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: local
domainZone: mangata.online
nameOverride: ''

remoteCluster: false
ingressClassName: nginx

image: "parity/polkadot:v0.9.38"

chain: rococo-local
storageClass: standard-rwo
storageSize: 10Gi
env_vars:
  RUST_LOG: info
aliceExtraArgs: []
bobExtraArgs: []
basePath: ''
chainspecPath: /etc/mangata/local.json
forceGenerateChainspec: false

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi