name: 'ci.yml'

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write     # For creating releases and committing changes
  packages: write     # For pushing to GitHub Container/OCI registry
  pull-requests: write # If you're creating PRs as part of your workflow

# Add concurrency to prevent multiple workflow runs from interfering with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          kubeconform: '0.6.7'
          helm: '3.17.1'
      - uses: 'moonrepo/setup-toolchain@v0'
      
      - run: moon ci :lint :kubeconform

      - run: moon :release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

