name: Validate Helm chart

on:
  pull_request:

jobs:
  helm-validate:
    name: Validate Node Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: kubeconform
      - name: Validate Helm Chart
        run: |
          helm lint charts/node
          helm template -f charts/node/values.yaml charts/node | kubeconform -kubernetes-version 1.24.5 -output json -summary -strict
          helm lint charts/relaychain-testnet
          helm template -f charts/relaychain-testnet/values.yaml charts/relaychain-testnet | kubeconform -kubernetes-version 1.24.5 -output json -summary -strict
