# Default values for mangata-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: local
domainZone: mangata.online
remoteCluster: false
storageClass: standard-rwo
command: /mangata/node

## Additional args to use
extraArgs: []
env:
  RUST_LOG: "info"

nameOverride: ''

image:
  repository: mangatasolutions/mangata-node
  pullPolicy: IfNotPresent
  ## Overrides the image tag whose default is the chart appVersion.
  tag: develop

isCollator: true
storageSize: 10Gi
## Example: `bootnodeAddr: /dns4/node-01/tcp/30333/p2p/12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x`
bootnodeAddr: ''
forceDownloadChainspec: true
chain: public-testnet
allowUnsafeRpcMethods: true
telemetryUrls: []
customChainspecPath: "/chain-data/chainspec.json"
## When defined, chainspec will be downloaded from the URL.
## By default `chain` variable value is passed to node's `--chain` parameter.
# customChainspecUrl:

chainData:
  snapshotFormat: lz4
  ## Configuration to download chain snapshot from remote URL
  ##
  # snapshotUrl: "https://dot-rocksdb.polkashots.io/snapshot"
  # chainPath: ""

## If configured, will assing custom node key for node instead of using
## generated one that is created and persisted on first run of the node
##
# customNodeKey:
# accountKeys:
# - type: aura
#   scheme: sr25519
#   seed: //Alice

enablePodMonitoringCollectors: false

parachainRegisterSidecar:
  enable: false
  image: mangatasolutions/parachain-register:1.1
  relaychainHostAddr: ws://relaychain-alice:9944
  parachainId: 2110
  command: []

relaychain:
  image: "parity/polkadot:v0.9.37"
  chain: rococo-local
  # bootnodeAddr: /dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
  storageSize: 10Gi
  ## When defined, chainspec will be downloaded from the URL.
  ## By default it is autogenerated using `rococo-local` chain configuration.
  # customChainspecUrl:
  chainspecPath: "/relaychain-data/relay_chain_chainspec.json"
  forceGenerateChainspec: false
  forceUseCustomChainspecPath: false
  chainData:
    snapshotFormat: lz4
    ## Configuration to download chain snapshot from remote URL
    ##
    # snapshotUrl: "https://dot-rocksdb.polkashots.io/snapshot"
    # chainPath: ""
    ## Specify this variable if there is an existing VolumeSnapshot in the SAME namespace
    ## to copy relaychaindata from.
    # kubernetesVolumeSnapshot: ""
  extraArgs: []

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

initContainer:
  image:
    repository: paritytech/lz4
    tag: latest
  debug: false
