# Default values for mangata-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: local
domainZone: mangata.online
remoteCluster: false

replicas: 1
nameOverride: ''

image:
  repository: mangatasolutions/mangata-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop

node:
  chain: public-testnet
  isCollator: true
  storageSize: 10Gi
  # Example: `bootnodeAddr: /dns4/node-01/tcp/30333/p2p/12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x`
  bootnodeAddr: ''
   # customChainspecUrl:
  customChainspecPath: "/chain-data/chainspec.json"
  forceDownloadChainspec: false
  accountKeys:
  - type: aura
    scheme: sr25519
    seed: //Alice
  env:
    RUST_LOG: "info"
  ## If configured, will assing custom node key for node instead of using
  ## generated one that is created and persisted on first run of the node
  ##
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000003"
  command: /mangata/node

relaychain:
  image: "parity/polkadot:v0.9.29"
  chain: rococo-local
  # customChainspecUrl:
  chainspecPath: "/relaychain-data/relay_chain_chainspec.json"
  storageSize: 10Gi
  bootnode: /dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
parachainRegisterSidecar:
  enable: false
  relaychainHostAddr: "ws://relaychain-alice:9944"
  parachainId: 2110

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
